# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# use_frameworks!

target 'GPUImageExample' do
  pod 'GPUImage'

end

target 'GPUSimpleVideoFilter' do
  pod 'GPUImage'

end
